WIP

diff --git a/source/mkpkg b/source/mkpkg
--- a/source/mkpkg
+++ b/source/mkpkg
@@ -1,48 +1,51 @@
 #!/bin/bash
-if [ $# -eq 0 ]; then
-    echo "Usage: mkpkg directory_name"
-else
-    DIR="$(dirname "$(readlink -f ${BASH_SOURCE[0]})")/${@}"
-    TMPDIR=/tmp/tmp.$(( $RANDOM * 19318203981230 + 40 ))
-    PLUGIN=$(basename ${DIR})
-    ARCHIVE="$(dirname $(dirname ${DIR}))/archive"
-    DESTDIR="$TMPDIR/usr/local/emhttp/plugins/${PLUGIN}"
-    PLG_FILE="$(dirname $(dirname ${DIR}))/plugin/${PLUGIN}.plg"
-    VERSION=$(date +"%Y.%m.%d")
-    ARCH="-x86_64-1"
-    PACKAGE="${ARCHIVE}/${PLUGIN}-${VERSION}${ARCH}.txz"
-    MD5="${ARCHIVE}/${PLUGIN}-${VERSION}${ARCH}.md5"
+NAME=NerdTools
+TMP_DIR=/${NAME}-temp
+PLUGIN_DIR="/plugin"
+ARCHIVE_DIR="/archive"
+VERSION=$(date +"%Y.%m.%d")
+PACKAGE_NAME="${NAME}-${VERSION}-x86_64-1"
 
+SRC_DIR=/source
+DEST_DIR="$TMP_DIR/usr/local/emhttp/plugins/${NAME}"
+PLG_FILE="${PLUGIN_DIR}/${NAME}.plg"
+PACKAGE_FILE="${ARCHIVE_DIR}/${PACKAGE_NAME}.txz"
+MD5_PATH="${ARCHIVE_DIR}/${PACKAGE_NAME}.md5"
 
-    for x in '' a b c d e d f g h ; do
-        PKG="${ARCHIVE}/${PLUGIN}-${VERSION}${x}${ARCH}.txz"
-        if [[ ! -f $PKG ]]; then
-          PACKAGE=$PKG
-          VERSION="${VERSION}${x}"
-          MD5="${ARCHIVE}/${PLUGIN}-${VERSION}${ARCH}.md5"
-          break
-        fi
-    done
+echo "NAME: $NAME"
+echo "TMP_DIR: $TMP_DIR"
+echo "PLUGIN_DIR: $PLUGIN_DIR"
+echo "ARCHIVE_DIR: $ARCHIVE_DIR"
+echo "VERSION: $VERSION"
+echo "PACKAGE_NAME: $PACKAGE_NAME"
+echo
+echo "DEST_DIR: $DEST_DIR"
+echo "PLG_FILE: $PLG_FILE"
+echo "PACKAGE_FILE: $PACKAGE_FILE"
+echo "MD5_PATH: $MD5_PATH"
 
-    sed -i -e "s#\(ENTITY\s*version[^\"]*\).*#\1\"${VERSION}\">#" "$PLG_FILE"
-    sed -i "/##&name/a\###${VERSION}" "$PLG_FILE"
+# sed -i -e "s#\(ENTITY\s*version[^\"]*\).*#\1\"${VERSION}\">#" "$PLG_FILE"
 
-    mkdir -p "${TMPDIR}/"
-    cd "$DIR"
-    cp --parents -f $(find . -type f ! \( -iname "pkg_build.sh" -o -iname "sftp-config.json" -o -iname ".DS_Store"  \) ) "${TMPDIR}/"
-    cd "$TMPDIR/"
-    makepkg -l y -c y "${PACKAGE}"
-    cd "$ARCHIVE/"
-    md5sum $(basename "$PACKAGE") > "$MD5"
-    rm -rf "$TMPDIR"
+mkdir -p "${TMP_DIR}/"
+cd "${SRC_DIR}"
 
-    # Verify and install plugin package
-    sum1=$(md5sum "${PACKAGE}")
-    sum2=$(cat "$MD5")
-    if [ "${sum1:0:32}" != "${sum2:0:32}" ]; then
-      echo "Checksum mismatched.";
-      rm "$MD5" "${PACKAGE}"
-    else
-      echo "Checksum matched."
-    fi
-fi
+cp --parents -f $(find . -type f ! \( -iname "mkpkg" \)) "${TMP_DIR}/"
+cd "$TMP_DIR"
+chmod 0755 -R "${TMP_DIR}/"
+chown root:root -R "${TMP_DIR}/"
+
+makepkg "${PACKAGE_FILE}" >/dev/null 2>&1 || echo "Error: makepkg failed" && exit 1
+#     cd "$ARCHIVE/"
+#     md5sum $(basename "$PACKAGE") >"$MD5"
+#     rm -rf "$TMPDIR"
+
+#     # Verify and install plugin package
+#     sum1=$(md5sum "${PACKAGE}")
+#     sum2=$(cat "$MD5")
+#     if [ "${sum1:0:32}" != "${sum2:0:32}" ]; then
+#         echo "Checksum mismatched."
+#         rm "$MD5" "${PACKAGE}"
+#     else
+#         echo "Checksum matched."
+#     fi
+# fi
